### PR TITLE
feat: set customElements at runtime

### LINKED ISSUE #36: vueCompilerOptions is not working
Thanks @huang-julien! The [nuxt-runtime-compiler](https://www.npmjs.com/package/nuxt-runtime-compiler) works well for us!

One thing...
We are using the `vue.compilerOptions.isCustomElement` option in the `nuxt.config.ts` as mentioned here: https://github.com/vuejs/core/issues/3746#issuecomment-835766808

(Because we are using [Katex](https://github.com/KaTeX/KaTeX))

Could it be that this configuration does not reach the runtime compiler?

_Originally posted by @abdonrd in https://github.com/nuxt/framework/issues/4762#issuecomment-1406632473_

### PR DESCRIPTION
**Pull request by huang-julien**
resolves #36

### CODE REVIEW

**Comment by abdonrd** [comment]
Thanks!

Could we allow the same thing that allows Vue? Receive a function:

https://vuejs.org/api/application.html#app-config-compileroptions-iscustomelement

In addition to MathML labels, we also usually use Web Components.

**Comment by huang-julien** [comment]
I'm currently investigating to see if we can directly retrieve the vue compiler options and pass it into the plugin template

**Comment by huang-julien** [comment]
Currently it is not possible to import the app.config.ts file within the module at build time since the file won't go through any transformation and is being imported as it is. 
If the user use the `defineAppConfig`, it won't be possible to import it and merge the compiler options with the build compilerOptions in the nuxt config since this is supposed to be auto-imported. 
If the user import `defineAppConfig` from `nuxt/app` the dynamic import will go through a max callstack since there seems to be some circular dependencies.
@abdonrd I think this is the only way to have the closest implementation of the `RuntimeCompilerOptions`. We canno't (yet) pass non stringifyable options such as function to plugin which are available a runtime.

**Comment by abdonrd** [comment]
Oh, we didn't know about the `app.config.ts`.

We only use the `nuxt.config.ts`:
```javascript
const mathmlTags = [/* ... */];
const isMathmlTag = (tag: string) => mathmlTags.includes(tag)

// ... 

  vue: {
    compilerOptions: {
      isCustomElement: (tag) => isMathmlTag(tag) || tag.startsWith('bx-'),
    },
  },
```

**Comment by huang-julien** [comment]
I think the current state of this PR should be acceptable since: 
- there's no way to pass non stringifyable options from modules to plugins
- There's currently no way to get the nuxt config in runtime
- We can't import the appConfig and use it to set the options also in build time. (i might open an issue in nuxt for this)

**Comment by abdonrd** [comment]
Got it!

And these problems would be solved if https://github.com/nuxt/framework/pull/4762 PR is accepted, right?

**Comment by huang-julien** [comment]
> Got it!
> 
> And these problems would be solved if [nuxt/framework#4762](https://github.com/nuxt/framework/pull/4762) PR is accepted, right?

i'm having the same issues with the PR. I keep it as a draft for now (i still need to redo the merge 😂 ).

**Comment by huang-julien** [comment]
I found a way (not very clean tho) to import the app config within the module and to set the RuntimeCompilerOptions into the builder context :+1:
This workaround should'nt be applied to the PR

**Pull request merged**
